// Generated by Wrangler by running `wrangler types`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface Env {
	STRIPE_SECRET_KEY?: string;
	STRIPE_PRICE_ID_MONTHLY?: string;
	STRIPE_PRICE_ID_YEARLY?: string;
	// OAuth
	GOOGLE_CLIENT_ID?: string;
	GOOGLE_CLIENT_SECRET?: string;
	GITHUB_CLIENT_ID?: string;
	GITHUB_CLIENT_SECRET?: string;
	SESSION_SECRET?: string;
	NODE_ENV?: string;
	APP_URL?: string;
}
